dist: trusty
language: cpp

matrix:
  include:
  - os: linux
    language: cpp
    compiler: gcc
    env:
        - COMPILER="g++-5"
        - STD_VER="-std=c++98"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - build-essential
        - cmake
        - libboost-all-dev
  - os: linux
    language: cpp
    compiler: clang
    env:
        - COMPILER="clang++-3.7"
        - STD_VER="-std=c++98"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        packages:
        - clang-3.7
        - build-essential
        - cmake
        - libboost-test-dev
  - os: osx
    language: cpp
    compiler: clang
    env: STD_VER="-std=c++98"
  - os: linux
    language: cpp
    compiler: gcc
    env:
        - COMPILER="g++-5"
        - STD_VER="-std=c++11"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - build-essential
        - cmake
        - libboost-all-dev
  - os: linux
    language: cpp
    compiler: clang
    env:
        - COMPILER="clang++-3.7"
        - STD_VER="-std=c++11"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        packages:
        - clang-3.7
        - build-essential
        - cmake
        - libboost-test-dev
  - os: osx
    language: cpp
    compiler: clang
    env: STD_VER="-std=c++11"

script:
- mkdir build
- cd build
- cmake -DCMAKE_CXX_COMPILER=${COMPILER} -DSTANDARD_VERSION:STRING=${STD_VER} ..
- make
- ctest --output-on-failure
